### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SecretPocketCat** [SecretPocketCat/unity-generator#1]
- [ ] switch to .NET Core
- [ ] unit tests
- [ ] make the *typed generics* generation more robust
- [ ] overhaul the `GenerateTypedClassAttribute`
- [ ] layers enum generation
- [ ] sorting layers enum generation
- [ ] switch to newer C# compilation for the attribute compilation
- [ ] tweak formatting (tabs/spaces) of generated code
- [ ] add a *generation path* option to the CMDs
- [ ] look into autorunning the tool (with watch) on Unity Start

**Comment by SecretPocketCat** [comment]
Addressed the editor subfolder issue in 03ad93919923f981a094ad0e0e23c6f730523355
